server:
  port: 8081
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?serverTimezone=GMT%2B8
    username: root
    password: 123456
#mybatis
mybatis:
  type-aliases-package: cn.itcast.pojo